### ISSUE TITLE
How to deal with the descending in retraining with all data in mode of ST++?

### ISSUE THREAD

**Issue by Qinger27** [LiheYoung/ST-PlusPlus#32] opened 2023-01-17 08:41 UTC
Hello, thanks for your great work first!
When I use your ST++ model in my dataset, the validation DICE of retraining on labeled and reliable data improved obviously. However, the validation DICE descreased in second retraining (on labeled and all unlabelled data). This situation wasn't  accidental, and it happened in many experiments. I thought a lot and didnot find a good way to figure out. Could you help me? And have you met this situation ever? What did you do to solve this problem?  
Thanks a lot.
Looking forward to your reply.

**Comment by LiheYoung** [comment] 2023-01-17 10:07
It is possible that selected unreliable images and their pseudo masks are too noisy to learn. To check this, could you calculate the Dice of pseudo masks of reliable and unreliable images respectively?

**Comment by Qinger27** [comment] 2023-01-18 09:20
> 
Thanks for your advise.
I calculated the dice of pseudo mask and gt, for reliable and unreliable data respectively. I found that some samples with high DICE could be chosen as unreliable and some samples with low DICE could be chosen as reliable. The mean DICE of reliable and unreliable are 0.76 and 0.58 respectively.  Your thought is right maybe. And could your give me some advise how to improve this situation? What should I do to improve the result of the second retraining?
Thanks again!
Looking forward to your reply.

**Comment by LiheYoung** [comment] 2023-01-19 09:04
Hi, it may be unavoidable that the automatic partition of reliable and unreliable samples is not perfect. 

To pursue higher performance, my tips, which may be not elegant, are that 
1) You do not need to strictly follow the 50%-50% partition, you can select top 75% samples as reliable ones. The remaining 25% unreliable ones are directly abandoned.  (The average dice 0.58 may be caused by a small portion of *extremely bad samples*.)
2) You can slightly change the training procedures. For example, you can first train on all labeled and pseudo labeled samples, and then finetune the model with labeled and reliable unlabeled samples.
3) You can additionally use a pixel-level threshold, *e.g.*, 0.95, to filter out unconfident pixels in unreliable images. In this case, you use all pixels in reliable images and only confident pixels in unreliable images for training.

I currently only think of these modifications. I will update this if I come up with better solutions.

**Comment by LiheYoung** [comment] 2023-01-29 06:34
I will close this issue. Please feel free to re-open it if you have further questions.

**Closed as completed** 2023-01-29 06:34 UTC
